(function(){
 'use strict';
 const C=FrotaCore,$=id=>document.getElementById(id);
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=n=>n===null||n===undefined?'Não informado':Number(n).toLocaleString('pt-BR',{maximumFractionDigits:2});
 const money=n=>n===null||n===undefined?'Não informado':Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const dt=d=>d?d.split('-').reverse().join('/'):'—';
 const span=x=>dt(x.data)+(x.data_fim!==x.data?' a '+dt(x.data_fim):'');
 const metrics=a=>C.executiveStats(a,dieselType);
 const opName=k=>C.OPS[k]||'A classificar';
 const groups=(a,key)=>C.groups(a,key).map(g=>({...g,stats:metrics(g.rows)}));
 let dieselType='S10';
 const consumption=s=>s.measuredKml!==null?num(s.measuredKml)+' km/L':'Sem litros/viagem concluída';
 const duration=x=>`<span class="tag ${C.days(x)>1?'f-duration':''}">${C.days(x)} ${C.days(x)>1?'dias':'dia'}</span>`;
 function marketPanel(a){const refs=[...new Map(a.map(x=>C.marketReference(x,dieselType)).filter(Boolean).map(ref=>[ref.place+ref.start,{ref,price:ref.price,source:ref.place+' · '+ref.type+' · '+ref.start+' a '+ref.end+(ref.fallback?' (última semana disponível)':'')}])).values()];return panel('Referência de mercado do diesel',`<label>Diesel da referência de mercado<select id="fDieselType">${option('S10','Diesel S10',dieselType)+option('S500','Diesel S500 comum',dieselType)}</select></label><p class="sub">Consulta ANP: 08/10/2026. São Paulo usa média municipal SP; Brasília usa média municipal DF. Fazenda usa média Brasil por não haver local de abastecimento confirmado. A operação é uma aproximação do local da compra, que pode ocorrer ao longo da rota. Referência apenas para comparação: não preenche os cálculos da litragem. Fora da semana pesquisada, mostra a última pesquisa anterior. Não há atualização automática da pesquisa.</p>`+table(['REFERÊNCIA UTILIZADA','PREÇO/L','FONTE'],refs.map(b=>'<tr>'+cell(b.source)+cell(money(b.price))+'<td><a href="'+escape(b.ref.source)+'" target="_blank" rel="noopener">ANP · pesquisa semanal</a></td></tr>').join('')));}
 function fuelSummary(a){const checks=C.alerts(a,records,config);return marketPanel(a)+(checks.length?panel('Análise e conferência',`<p class="sub danger">${checks.length} alertas nos registros deste filtro. Saltos de hodômetro podem inflar o KM/L; confira os dados antes de planejar viagens. O gasto abastecido pode incluir combustível para outros dias. Compare veículos de porte, carga e percurso semelhantes.</p>`):'')+panel('KM/L e preço por litro por caminhão',`<p class="sub">L/KM = litros ÷ KM. KM/L = KM ÷ litros. Preço/L = gasto em DIESEL ÷ litros. Sem litros, calculamos gasto ÷ preço/L pago informado. Apenas gasto e KM não determinam litros ou preço exatos. A referência de mercado não substitui o preço pago. Colunas estimadas usam gasto ÷ referência ANP e são exibidas separadamente; não são medidas exatas. Razões do período incluem dias sem abastecimento; consumo real exige conciliar o saldo do tanque. Pedágio não entra no diesel.</p>`+table(['CAMINHÃO','KM','LITROS INFORMADOS/CALCULADOS','L/KM CALCULADO','KM/L','PREÇO PAGO MÉDIO/L','LITROS ESTIMADOS','L/KM ESTIMADO','PREÇO DE REFERÊNCIA/L'],groups(a,'placa').map(g=>'<tr><td>'+action('truck',g.name,g.name)+'</td>'+cell(num(g.stats.km))+cell(num(g.stats.effectiveLiters)+(g.stats.derivedLiters?' (calculados)':''))+cell(g.stats.litersPerKm===null?'Não informado':Number(g.stats.litersPerKm).toLocaleString('pt-BR',{maximumFractionDigits:4})+' L/km')+cell(consumption(g.stats))+cell(money(g.stats.price))+cell(g.stats.estimate.market?num(g.stats.estimate.liters):'—')+cell(g.stats.estimate.market&&g.stats.estimate.lpkm!==null?g.stats.estimate.lpkm.toLocaleString('pt-BR',{maximumFractionDigits:4}):'—')+cell(g.stats.estimate.market?money(g.stats.estimate.price):'—')+'</tr>').join('')));}
 const option=(value,label,selected)=>`<option value="${escape(value)}" ${value===selected?'selected':''}>${escape(label)}</option>`;
 const opOptions=selected=>Object.entries(C.OPS).map(([k,v])=>option(k,v,selected)).join('');
 let records=[],expenses=[],executive=[],imports=[],config={fator_custo:1.5,fator_km:3},active=false,page='overview',detail=null,preview=null,busy=false,loaded=false,loadError='',selected=new Set();
 const titles={overview:['Frota','Gestão operacional e financeira da frota Premier Logística'],trucks:['Caminhões','Visão operacional dos veículos da frota'],drivers:['Motoristas','Histórico de utilização dos veículos por motorista'],fuel:['Combustível','Gastos conhecidos e abastecimentos da frota'],tolls:['Pedágios','Despesas de pedágio por veículo e operação'],operations:['Operações','Premier São Paulo, Premier Brasília e Premier Fazenda'],sheets:['Planilhas','Importar e exportar dados compartilhados da frota'],settings:['Configurações','Parâmetros de conferência da frota']};
 const oldLive=document.querySelector('.top .live');
 const fLive=document.createElement('div');fLive.className='live';fLive.hidden=true;fLive.innerHTML='<span class="dot" id="fSyncDot"></span><span id="fSync">Carregando frota...</span>';document.querySelector('.top').append(fLive);
 document.querySelector('nav').insertAdjacentHTML('beforeend',`<button class="km-toggle frota-toggle" id="fToggle" type="button" aria-expanded="false" aria-controls="fMenu"><span>▣ Dashboard da Frota</span><span class="km-chevron" aria-hidden="true">⌄</span></button><div id="fMenu" class="km-menu" hidden>${Object.entries(titles).map(([k,v])=>`<a role="button" tabindex="0" data-fpage="${k}">${escape(v[0]==='Frota'?'Visão Geral':v[0])}</a>`).join('')}</div>`);
 const root=document.createElement('section');root.id='frotaRoot';root.className='page';root.innerHTML=`<div class="notice" id="fNotice" hidden role="status"></div><div class="filters" id="fFilters"><label>Período inicial<input type="date" id="fStart"></label><label>Período final<input type="date" id="fEnd"></label><label>Operação<select id="fOp">${option('','Todas','')+opOptions('')}</select></label><label>Placa<select id="fPlate"><option value="">Todas</option></select></label><label>Motorista<select id="fDriver"><option value="">Todos</option></select></label><button data-action="reset">Limpar filtros</button></div><div id="fContent"></div></section>`;document.querySelector('main').append(root);
 const dialog=document.createElement('dialog');dialog.id='fDialog';dialog.innerHTML='<h2 id="fFormTitle">Registro da frota</h2><form id="fForm"><div class="f-form" id="fFormFields"></div><p id="fFormError" role="alert"></p><div class="bulk"><button type="button" id="fCancel">Cancelar</button><button type="submit" id="fSave">Salvar para todos</button></div></form>';document.body.append(dialog);
 const oldGo=window.go;window.go=function(id,el){active=false;oldLive.hidden=false;fLive.hidden=true;oldGo(id,el);};
 async function request(path,options={}){
  const r=await fetch(U+'/rest/v1/'+path,{...options,headers:{apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});
  if(!r.ok){let e;try{e=await r.json();}catch{e={message:r.statusText};}throw Error(e.message||'Falha de comunicação ('+r.status+')');}const text=await r.text();return text?JSON.parse(text):[];
 }
 async function paginated(table,query){let result=[];for(let offset=0;;offset+=1000){const batch=await request(table+'?'+query+'&limit=1000&offset='+offset);result.push(...batch);if(batch.length<1000)return result;if(offset>1000000)throw Error('Limite de consulta excedido');}}
 async function loadFleet(){
  if(busy)return;
  try{
   const [r,i,c,e]=await Promise.all([paginated('frota_registros','select=*&deleted_at=is.null&order=data.asc,id.asc'),request('frota_importacoes?select=id,arquivo,recebido,importado,duplicado,created_at&order=id.desc&limit=50'),request('frota_config?select=*&id=eq.1'),paginated('frota_despesas','select=*&deleted_at=is.null&order=data.asc,id.asc')]);
   records=r.map(x=>{const y={...x};for(const k of ['km_inicial','km_final','km_declarado','km_total','diesel','litros','preco_litro','pedagio'])y[k]=x[k]===null?null:Number(x[k]);return y;});expenses=e.map(x=>({...x,valor:Number(x.valor),litros:x.litros===null?null:Number(x.litros),preco_litro:x.preco_litro===null?null:Number(x.preco_litro)}));executive=C.expenseRows(records,expenses);imports=i;config=c[0]||config;loaded=true;loadError='';updateOptions();if(active)render();$('fSync').textContent='Sincronizado para todos';$('fSyncDot').style.background='var(--green)';
  }catch(e){loadError=e.message;$('fSync').textContent='Frota não sincronizada';$('fSyncDot').style.background='var(--red)';if(active)render();}
 }
 function updateOptions(){if(executive.some(x=>x.operacao==='PEND')&&!$('fOp').querySelector('[value="PEND"]'))$('fOp').insertAdjacentHTML('beforeend',option('PEND','A classificar',''));const p=$('fPlate').value,d=$('fDriver').value;const scoped=C.filtered(executive,{operation:$('fOp').value});$('fPlate').innerHTML=option('','Todas','')+[...new Set(scoped.map(x=>x.placa))].sort().map(x=>option(x,x,p)).join('');$('fDriver').innerHTML=option('','Todos','')+[...new Set(scoped.map(x=>x.motorista))].sort().map(x=>option(x,x,d)).join('');}
 function filters(){return {start:$('fStart').value,end:$('fEnd').value,operation:$('fOp').value,plate:$('fPlate').value,driver:$('fDriver').value};}
 function rows(){return C.filtered(executive,filters());}
 function navigate(to,el){active=true;page=to;detail=null;document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));root.classList.add('on');document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));(el||document.querySelector('[data-fpage="'+to+'"]')).classList.add('active');oldLive.hidden=true;fLive.hidden=false;$('title').textContent=titles[to][0];$('subtitle').textContent=titles[to][1];render();if(!loaded)loadFleet();}
 function notice(message,warn=false){const el=$('fNotice');el.hidden=!message;el.textContent=message;el.className='notice'+(warn?' warn':'');}
 function cards(list){return '<div class="cards">'+list.map(([label,value,sub='',cls=''])=>`<div class="card ${cls}"><div class="cap">${escape(label)}</div><div class="val">${escape(value)}</div>${sub?`<div class="sub">${escape(sub)}</div>`:''}</div>`).join('')+'</div>';}
 function panel(title,content,extra=''){return `<div class="panel ${extra}"><div class="ph"><h2>${escape(title)}</h2></div>${content}</div>`;}
 function table(headers,body){return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}"><div class="empty">Nenhum registro neste filtro.</div></td></tr>`}</tbody></table></div>`;}
 const cell=value=>`<td>${escape(value)}</td>`;
 const action=(name,id,label,cls='')=>`<button class="row-link ${cls}" data-action="${name}" data-id="${escape(id)}">${escape(label)}</button>`;
 function timeline(a){const by=new Map();a.forEach(x=>{if(x.km_total!==null)by.set(x.data_fim,(by.get(x.data_fim)||0)+x.km_total);});const ar=[...by].sort(),max=Math.max(1,...ar.map(x=>x[1]));if(!ar.length)return '<div class="empty">Sem KM informado para o gráfico.</div>';return '<div class="chart">'+ar.map(([day,km])=>`<div class="day" title="${dt(day)}: ${num(km)} km"><div class="bar a" style="height:${km/max*100}%"></div><span>${dt(day).slice(0,5)}</span></div>`).join('')+'</div><p class="sub">Viagens com intervalo são mostradas na data de conclusão, sem repartir o KM.</p>';}
 function bars(a,key,format=money){const max=Math.max(1,...a.map(x=>x.stats[key]??0));if(!a.length)return '<div class="empty">Sem dados para comparar.</div>';return '<div class="mini-bars">'+a.map(x=>`<div class="mini-row"><b>${escape(x.name)}</b><div class="mini-track"><div class="mini-fill" style="width:${(x.stats[key]??0)/max*100}%"></div></div><span>${escape(format(x.stats[key]))}</span></div>`).join('')+'</div>';}
 function recordTable(a,withActions=false){return table(withActions?['','DATA','PLACA','MOTORISTA','OPERAÇÃO','KM','COMBUSTÍVEL','PEDÁGIO','AÇÕES']:['DATA','MOTORISTA','KM INICIAL','KM FINAL','KM TOTAL','COMBUSTÍVEL','PEDÁGIO','OPERAÇÃO'],a.slice().sort(C.order).reverse().map(x=>'<tr>'+(withActions?`<td><input class="f-check" type="checkbox" aria-label="Selecionar registro ${x.id}" data-id="${x.id}" ${selected.has(x.id)?'checked':''}></td>`+cell(span(x))+cell(x.placa)+cell(x.motorista)+cell(opName(x.operacao))+cell(x.km_total===null?'Pendente':num(x.km_total))+cell(money(x.diesel))+cell(money(x.pedagio))+`<td>${action('edit',x.id,'Editar')} ${action('delete',x.id,'Excluir','danger')}</td>`:cell(span(x))+cell(x.motorista)+cell(num(x.km_inicial))+cell(num(x.km_final))+cell(num(x.km_total))+cell(money(x.diesel))+cell(money(x.pedagio))+cell(opName(x.operacao)))+'</tr>').join(''));}
 function expenseList(a,tipo){const ids=new Set(a.flatMap(x=>(x.despesas||[]).map(e=>e.id)));return expenses.filter(e=>ids.has(e.id)&&(!tipo||e.tipo===tipo));}
 function expenseTable(a,tipo){const e=expenseList(a,tipo);return table(tipo==='pedagio'?['DATA','HORÁRIO','PLACA','TIPO DE VEÍCULO','DESCRIÇÃO / LOCAL / SENTIDO','VALOR','DÉBITO/CRÉDITO','OPERAÇÃO / VÍNCULO','DETALHES']:['DATA','PLACA','OPERAÇÃO','DIESEL','LITROS','PREÇO CALCULADO/L','PREÇO INFORMADO/L','CONFERÊNCIA'],e.slice().reverse().map(x=>{const source=Object.entries(x.origem?.colunas||{}).map(([k,v])=>'<div><b>'+escape(k)+':</b> '+escape(v)+'</div>').join('');return '<tr data-toll-search="'+escape(C.normalize([x.data,x.horario,x.placa,x.observacao,x.tipo_veiculo,x.natureza].join(' ')))+'">'+cell(dt(x.data))+(tipo==='pedagio'?cell(x.horario)+cell(x.placa)+cell(x.tipo_veiculo)+cell(x.observacao||x.praca)+cell(money(x.valor))+cell(x.natureza)+cell(opName(x.operacao)+(x.registro_id?' · viagem #'+x.registro_id:' · vínculo pendente'))+'<td><details><summary>Todos os dados</summary>'+source+'<p>'+escape(x.origem?.arquivo||'Registro manual')+' · linha '+escape(x.origem?.linha||'—')+'</p></details></td>':cell(x.placa)+cell(opName(x.operacao))+cell(money(x.valor))+cell(num(x.litros))+cell(money(C.ratio(x.valor,x.litros)))+cell(money(x.preco_litro))+cell(x.litros&&x.preco_litro&&Math.abs(x.valor-x.litros*x.preco_litro)>.1?'Valor e preço informado divergentes':'Dados do comprovante'))+'</tr>';}).join(''));}
 function opComparison(a){return table(['OPERAÇÃO','KM','Δ KM ANTERIOR','DIESEL','PEDÁGIOS','CUSTO/KM','KM/L¹','PREÇO PAGO/L'],groups(a,'operacao').map(g=>'<tr>'+cell(opName(g.name))+cell(num(g.stats.km))+cell((()=>{const c=C.comparisonPeriods(executive,{...filters(),operation:g.name});return c?.difference===null||!c?'Sem base':(c.difference>0?'+':'')+num(c.difference)+' km';})())+cell(money(g.stats.fuel))+cell(money(g.stats.toll))+cell(money(g.stats.cpkm))+cell(consumption(g.stats))+cell(money(g.stats.actualPrice))+'</tr>').join(''))+'<p class="sub">¹ Apenas viagens concluídas com KM e litros. Preço/L ponderado = diesel ÷ litros. Custos sem viagem vinculada entram no total; não fornecem KM para calcular eficiência.</p>';}
 function evolutionChart(a,cumulative=false){const points=C.evolution(a),keys=Object.keys(C.OPS),colors=['#4a8cff','#17c9d1','#9a77ec'];if(!points.length)return '<div class="empty">Sem KM registrado.</div>';const max=Math.max(1,...points.flatMap(x=>keys.map(k=>x[cumulative?'cumulative':'increment'][k])));return '<svg viewBox="0 0 760 250" role="img" aria-label="Evolução de quilômetros por operação" style="width:100%;min-height:200px">'+[0,1,2,3,4].map(i=>'<text x="0" y="'+(215-i*48)+'" fill="#8b97ac" font-size="12">'+escape(num(max*i/4))+'</text><line x1="65" y1="'+(210-i*48)+'" x2="740" y2="'+(210-i*48)+'" stroke="#26334a"/>').join('')+keys.map((k,i)=>'<polyline fill="none" stroke="'+colors[i]+'" stroke-width="3" points="'+points.map((x,j)=>(65+j*675/Math.max(1,points.length-1))+','+(210-x[cumulative?'cumulative':'increment'][k]/max*192)).join(' ')+'"/>'+points.map((x,j)=>'<circle cx="'+(65+j*675/Math.max(1,points.length-1))+'" cy="'+(210-x[cumulative?'cumulative':'increment'][k]/max*192)+'" r="4" fill="'+colors[i]+'"><title>'+escape(dt(x.date)+' · '+opName(k)+' · aumento '+num(x.increment[k])+' km · acumulado '+num(x.cumulative[k])+' km')+'</title></circle>').join('')).join('')+points.filter((x,i)=>i===0||i===points.length-1||i%4===0).map(x=>'<text x="'+(65+points.indexOf(x)*675/Math.max(1,points.length-1))+'" y="240" text-anchor="middle" fill="#8b97ac" font-size="11">'+dt(x.date).slice(0,5)+'</text>').join('')+'</svg><p class="sub">'+keys.map((k,i)=>'<span style="color:'+colors[i]+'">● '+escape(opName(k))+'</span>').join(' · ')+'</p><p class="sub">Passe sobre os pontos para consultar aumento e acumulado. KM na última data informada; viagens em andamento têm KM parcial.</p>';}
 function overview(a){const s=metrics(a),c=C.comparisonPeriods(executive,filters()),t=expenseList(a,'pedagio');return cards([['KM RODADO',num(s.km)+' km',s.ongoing+' viagem em andamento','cyan'],['DIESEL',money(s.fuel),'Valores conhecidos'],['PEDÁGIOS',money(s.toll),t.length+' passagens detalhadas'],['CUSTO CONHECIDO',money(s.cost),'Diesel + pedágio'],['CUSTO/KM',money(s.cpkm),'Custos conhecidos ÷ KM informado'],['LITROS ABASTECIDOS',num(s.actualLiters)+' L','Litragem fornecida'],['KM/L · CONCLUÍDAS',consumption(s),num(s.measuredKm)+' km com base em litros'],['PREÇO PAGO/L',money(s.actualPrice),'Média ponderada dos abastecimentos']])+panel('Comparativo de KM do período',c?cards([['PERÍODO ATUAL',num(c.currentKm)+' km',dt(c.start)+' a '+dt(c.end)],['PERÍODO ANTERIOR',c.previousKm===null?'Sem histórico':num(c.previousKm)+' km',dt(c.previousStart)+' a '+dt(c.previousEnd)],['VARIAÇÃO DE KM',c.difference===null?'Sem base':(c.difference>0?'+':'')+num(c.difference)+' km',c.percent===null?'Selecione um período com histórico anterior':num(c.percent)+'%']]):'<p>Sem dados.</p>')+`<div class="grid">${panel('KM acumulado por operação',evolutionChart(a,true))}${panel('Aumento de KM por operação',evolutionChart(a))}</div>`+panel('Comparativo executivo das operações',opComparison(a))+`<div class="grid">${panel('Diesel por caminhão',bars(groups(a,'placa'),'fuel'))}${panel('Pedágios por operação',bars(groups(a,'operacao').map(g=>({...g,name:opName(g.name)})),'toll'))}</div>`+panel('Pedágios incluídos na visão geral',`<p>${t.length} passagens · ${money(t.reduce((n,x)=>n+x.valor,0))} na planilha detalhada · ${t.filter(x=>!x.registro_id).length} vínculos de viagem pendentes.</p><button data-action="open-tolls">Consultar todas as passagens</button>`);}

 function trucks(a){return panel('Custos e eficiência por caminhão',table(['PLACA','KM','DIESEL','LITROS','KM/L · CONCLUÍDAS','PREÇO/L','PEDÁGIOS','CUSTO/KM'],groups(a,'placa').map(g=>'<tr><td>'+action('truck',g.name,g.name)+'</td>'+cell(num(g.stats.km))+cell(money(g.stats.fuel))+cell(num(g.stats.actualLiters))+cell(consumption(g.stats))+cell(money(g.stats.actualPrice))+cell(money(g.stats.toll))+cell(money(g.stats.cpkm))+'</tr>').join(''))+'<p class="sub">KM/L considera somente viagens concluídas com litragem. Clique na placa para consultar o histórico.</p>')+panel('Comparação de litros abastecidos',bars(groups(a,'placa'),'actualLiters',n=>num(n)+' L'));}
 function drivers(a){return panel('Motoristas',table(['NOME','ÚLTIMO CAMINHÃO','OPERAÇÃO','KM','COMBUSTÍVEL','PEDÁGIO','CUSTO/KM'],groups(a,'motorista').map(g=>`<tr><td>${action('driver',g.name,g.name)}</td>${cell(g.last.placa)}${cell(C.OPS[g.last.operacao])}${cell(num(g.stats.km))}${cell(money(g.stats.fuel))}${cell(money(g.stats.toll))}${cell(money(g.stats.cpkm))}</tr>`).join('')));}
 function fuel(a){const s=metrics(a);return cards([['DIESEL',money(s.fuel)],['LITROS',num(s.actualLiters)+' L'],['PREÇO PAGO/L',money(s.actualPrice)],['KM/L · CONCLUÍDAS',consumption(s)]])+panel('Abastecimentos e conferência de preço',expenseTable(a,'diesel'))+panel('Gastos específicos por veículo',bars(groups(a,'placa'),'fuel'))+'<details>'+marketPanel(a)+'</details><p class="sub">Litros são os abastecidos. Consumo efetivo exige conciliar saldo inicial e final do tanque. Preço informado no comprovante é preservado mesmo quando diverge de valor ÷ litros.</p>';}
 function tolls(a){const s=metrics(a),e=expenseList(a,'pedagio');return cards([['PEDÁGIOS',money(s.toll),'Valores detalhados substituem o total antigo da mesma viagem'],['PASSAGENS',num(e.length)],['VÍNCULOS PENDENTES',num(e.filter(x=>!x.registro_id).length),'Incluídos no custo geral'],['PEDÁGIO/KM',money(s.tpkm),'Razão dos valores e KM conhecidos']])+`<div class="grid">${panel('Pedágios por veículo',bars(groups(a,'placa'),'toll'))}${panel('Pedágios por operação',bars(groups(a,'operacao').map(g=>({...g,name:opName(g.name)})),'toll'))}</div>`+panel('Todas as informações da planilha de pedágios','<input class="f-search" id="fSearchToll" placeholder="Pesquisar placa, rodovia, cidade ou horário" aria-label="Pesquisar pedágios">'+expenseTable(a,'pedagio'));}
 function operations(a){return panel('Comparativo detalhado das operações',opComparison(a))+panel('Datas, duração e custos das viagens',table(['OPERAÇÃO / VIAGEM','PLACA','INÍCIO','FIM / STATUS','DIAS','KM','DIESEL','PEDÁGIOS','DETALHES'],a.filter(x=>!x.sem_vinculo).slice().sort(C.order).reverse().map(x=>'<tr>'+cell(opName(x.operacao)+(x.viagem?' · '+x.viagem:''))+cell(x.placa)+cell(dt(x.data))+cell(x.em_andamento?'Em andamento · última atualização '+dt(x.data_fim):dt(x.data_fim))+'<td>'+duration(x)+(x.em_andamento?' (até atualização)':'')+'</td>'+cell(num(x.km_total)+(x.em_andamento?' (parcial)':''))+cell(money(x.diesel))+cell(money(x.pedagio))+'<td><details><summary>Ver análise</summary><p>Motorista: '+escape(x.motorista)+' · KM/L: '+escape(consumption(metrics([x])))+' · preço/L: '+escape(money(metrics([x]).actualPrice))+' · custo/KM: '+escape(money(metrics([x]).cpkm))+'</p>'+expenseTable([x],'diesel')+expenseTable([x],'pedagio')+'</details></td></tr>').join('')))+`<details><summary>Administrar registros da frota</summary>${panel('Registros originais',`<div class="bulk"><button data-action="add">Adicionar registro</button></div>`+recordTable(C.filtered(records,filters()),true))}</details>`;}
 function detailView(a){const isTruck=detail.type==='truck',subset=a.filter(x=>x[isTruck?'placa':'motorista']===detail.name),s=metrics(subset),last=subset.slice().sort(C.order).at(-1);if(!last)return '<button data-action="back-detail">Voltar</button><div class="empty">Sem registros neste filtro.</div>';return `<div class="bulk"><button data-action="back-detail">Voltar</button><h2>${escape(detail.name)}</h2></div>`+cards([
  ['ÚLTIMA OPERAÇÃO',opName(last.operacao)],['ÚLTIMO '+(isTruck?'MOTORISTA':'CAMINHÃO'),isTruck?last.motorista:last.placa],['KM ACUMULADO',num(s.km)+' km'],['COMBUSTÍVEL',money(s.fuel)],['PEDÁGIO',money(s.toll)],['CUSTO/KM',money(s.cpkm)],['KM/L',consumption(s),'Razão do período; depende dos litros ou preço pago'],['PREÇO/L PARA ANÁLISE',money(s.actualPrice),'Preço pago médio ponderado'],['ÚLTIMA UTILIZAÇÃO',dt(last.data_fim)],['STATUS',s.pending?'Conferir KM pendente':'Com registros']])+panel('Evolução de KM',timeline(subset))+panel('Passagens detalhadas do veículo',expenseTable(subset,'pedagio'))+`<div class="detail-panel">${panel(isTruck?'Motoristas que utilizaram o veículo':'Caminhões utilizados',table(['NOME','KM','REGISTROS'],groups(subset,isTruck?'motorista':'placa').map(g=>'<tr>'+cell(g.name)+cell(num(g.stats.km))+cell(g.rows.length)+'</tr>').join('')))}</div>`+`<div class="detail-panel">${panel('Histórico operacional',recordTable(subset))}</div>`+`<div class="grid detail-panel">${panel('Combustível',table(['DATA','VALOR','LITROS'],subset.filter(x=>x.diesel!==null||x.litros!==null).map(x=>'<tr>'+cell(span(x))+cell(money(x.diesel))+cell(num(x.litros))+'</tr>').join('')))}${panel('Pedágios',table(['DATA','VALOR','ROTA'],subset.filter(x=>x.pedagio!==null).map(x=>'<tr>'+cell(span(x))+cell(money(x.pedagio))+cell(x.rota)+'</tr>').join('')))}</div>`;}
 function sheets(){return `<div class="grid f-import-grid">${panel('Importar planilha',`<p class="sub">DATA, OPERAÇÃO, MOTORISTA, PLACA, KM INICIAL, KM FINAL, KM TOTAL, VALOR DIESEL, LITROS, PREÇO/LITRO, PEDÁGIO, PONTO DE PARTIDA, DESTINO/ROTA e OBSERVAÇÃO. DATA FIM é opcional para viagens com intervalo.</p><button style="width:100%;margin-bottom:12px" data-action="template">Baixar layout para importação</button><label>Na planilha antiga, “premier” corresponde a<select id="fDefaultOp">${opOptions('SP')}</select></label><p class="sub">“fazenda” → Premier Fazenda. Brasília explícita na descrição → Premier Brasília. Confira as operações na prévia.</p><input class="file-input" id="fFile" type="file" accept=".xlsx,.xls,.ods,.csv" aria-label="Escolher arquivo da frota"><button style="width:100%;margin-top:12px" data-action="preview">Importar para todos</button><p class="sub">A prévia será apresentada antes de gravar. Campos vazios permanecem não informados.</p>`)}${panel('Exportar planilha',`<p class="sub">Inclui dados originais, KM calculado, custos e conferências. Todas as operações e todo o histórico ativo.</p><div class="val">${records.length} registros</div><button style="width:100%;margin-top:12px" data-action="export">Exportar Excel</button><p class="sub">A aba IMPORTAÇÃO permite reimportar os dados sem duplicá-los.</p>`)}</div><div id="fPreview"></div>${panel('Histórico de importações',table(['DATA','ARQUIVO','RECEBIDOS','IMPORTADOS','DUPLICADOS'],imports.map(x=>'<tr>'+cell(new Date(x.created_at).toLocaleString('pt-BR'))+cell(x.arquivo)+cell(x.recebido)+cell(x.importado)+cell(x.duplicado)+'</tr>').join('')))}`;}
 function settings(){return panel('Parâmetros compartilhados',`<p class="sub">Alertas são comparações para conferência, não prova de erro. Use os parâmetros conforme a operação.</p><label>Custo/KM acima de quantas vezes a mediana da operação?<input id="fCostFactor" type="number" min="1.01" max="10" step="0.1" value="${config.fator_custo}"></label><p class="sub">Exige pelo menos três placas comparáveis na operação. Padrão 1,5×: sinaliza valores 50% acima da mediana.</p><label>KM/dia acima de quantas vezes a mediana histórica da placa?<input id="fKmFactor" type="number" min="1.01" max="20" step="0.1" value="${config.fator_km}"></label><p class="sub">Exige pelo menos cinco registros com KM. Padrão 3×: serve para triagem de saltos grandes, sem corrigir valores automaticamente.</p><button data-action="settings-save">Salvar para todos</button><p class="sub">Custos conhecidos não incluem manutenção, pneus ou despesas ausentes. Ativos são placas/motoristas com registros no período. Viagens com intervalo entram por inteiro quando cruzam o filtro.</p>`);}
 function render(){
  $('fFilters').hidden=['sheets','settings'].includes(page);
  if(loadError){notice('Não foi possível sincronizar a frota: '+loadError+'. Os dados de KM continuam disponíveis.',true);}else if(loaded){notice('');}else notice('Carregando dados compartilhados da frota...');
  const f=filters();if(f.start&&f.end&&f.end<f.start){notice('O fim do período deve ser igual ou posterior ao início.',true);$('fContent').innerHTML='';return;}
  const a=rows();$('fContent').innerHTML=detail?detailView(a):({overview,trucks,drivers,fuel,tolls,operations,sheets,settings}[page])(a);
  if(page==='sheets'&&preview)renderPreview();
 }
 function renderPreview(){
  if(!$('fPreview')||!preview)return;const valid=preview.rows.filter(x=>x.record&&!x.error&&!x.duplicate),bad=preview.rows.filter(x=>x.error),duplicates=preview.rows.filter(x=>x.duplicate),warnings=preview.rows.filter(x=>x.warnings.length);
  $('fPreview').innerHTML=panel('Prévia da importação',`<p>${preview.rows.length} linhas · ${valid.length} disponíveis · ${duplicates.length} duplicadas · ${bad.length} bloqueadas · ${warnings.length} com avisos.</p><p class="sub">Revise as operações e marque as linhas que deseja importar. Linhas bloqueadas não serão gravadas. Valores divergentes não são corrigidos por adivinhação.</p>${preview.issues.map(x=>`<p class="danger">${escape(x)}</p>`).join('')}<div class="f-preview">${table(['IMPORTAR','LINHA','DATA','PLACA','MOTORISTA','OPERAÇÃO','KM','DIESEL','CONFERÊNCIA'],preview.rows.map((item,i)=>{const x=item.record;return `<tr><td><input type="checkbox" data-preview-index="${i}" ${item.selected?'checked':''} ${item.error||item.duplicate?'disabled':''} aria-label="Importar linha ${item.line}"></td>${cell(item.sheet+' / '+item.line)}${cell(x?span(x):'—')}${cell(x?.placa??'—')}${cell(x?.motorista??'—')}<td>${x?`<select data-preview-operation="${i}" aria-label="Operação da linha ${item.line}">${opOptions(x.operacao)}</select>`:'—'}</td>${cell(x?num(x.km_total):'—')}${cell(x?money(x.diesel):'—')}<td class="notes ${item.error?'danger':''}">${escape(item.error|| (item.duplicate?'Duplicado: não será importado':item.warnings.join('; ')||'Validado'))}</td></tr>`;}).join(''))}</div><div class="bulk" style="margin-top:14px"><button data-action="confirm-import" ${busy?'disabled':''}>Confirmar importação</button><button data-action="cancel-preview">Cancelar prévia</button></div>`,'detail-panel');
 }
 function exportWorkbook(template=false){
  if(typeof XLSX==='undefined')throw Error('Leitor de planilhas indisponível. Atualize a página.');
  const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(template?[]:C.exportRows(records),{header:C.HEADERS});ws['!cols']=C.HEADERS.map(h=>({wch:Math.max(16,h.length+2)}));
  XLSX.utils.book_append_sheet(wb,ws,'IMPORTAÇÃO');
  if(template){const guide=XLSX.utils.aoa_to_sheet([['INSTRUÇÕES'],['Operações: Premier São Paulo, Premier Brasília ou Premier Fazenda.'],['Datas: dd/mm/aaaa. DATA FIM opcional para viagem com intervalo.'],['KM TOTAL calculado por KM FINAL - KM INICIAL quando ambos estiverem preenchidos.'],['Valores e litros: números. Campos não informados devem ficar vazios; zero significa zero confirmado.'],['Datas e motoristas obrigatórios; placa formato ABC1234 ou ABC1D23.'],['Cada linha representa uma utilização/viagem. Inclua todos os dados conhecidos.'],['Não misture totais/subtotais entre os registros. Revise a prévia antes de confirmar.']]);guide['!cols']=[{wch:110}];XLSX.utils.book_append_sheet(wb,guide,'INSTRUÇÕES');}
  else {const report=executive.map(x=>({'DATA':x.data,'DATA FIM':x.data_fim,'DURAÇÃO DIAS':C.days(x),'PLACA':x.placa,'MOTORISTA':x.motorista,'OPERAÇÃO':C.OPS[x.operacao],'KM CALCULADO':x.km_total??'','COMBUSTÍVEL':x.diesel??'','PEDÁGIO':x.pedagio??'','CUSTO CONHECIDO':x.diesel===null&&x.pedagio===null?'':(x.diesel??0)+(x.pedagio??0),'CUSTO/KM':metrics([x]).cpkm??'','LITROS CALCULADOS':metrics([x]).effectiveLiters??'','L/KM CALCULADO':metrics([x]).litersPerKm??'','KM/L CALCULADO':metrics([x]).measuredKml??'','PREÇO PAGO/L':C.fuelBasis(x,dieselType).price??'','LITROS ESTIMADOS':C.estimate([x],dieselType).market?(C.estimate([x],dieselType).liters??''):'','KM/L ESTIMADO':C.estimate([x],dieselType).market?(C.estimate([x],dieselType).kml??''):'','PREÇO REFERÊNCIA/L':C.marketReference(x,dieselType)?.price??'','FONTE REFERÊNCIA':C.marketReference(x,dieselType)?.source??'','CONFERÊNCIA':C.alerts([x],records,config).map(a=>a.message).join('; ')}));const rpt=XLSX.utils.json_to_sheet(report);rpt['!cols']=Array.from({length:11},()=>({wch:22}));XLSX.utils.book_append_sheet(wb,rpt,'RELATÓRIO');}
  if(!template){for(const tipo of ['diesel','pedagio']){const data=expenses.filter(x=>x.tipo===tipo).map(x=>({...x.origem?.colunas,DATA:x.data,HORARIO:x.horario,PLACA:x.placa,'TIPO VEICULO':x.tipo_veiculo,DESCRICAO:x.observacao,VALOR:x.valor,'DEBITO/CREDITO':x.natureza,OPERACAO:opName(x.operacao),'VIAGEM ID':x.registro_id??'',LITROS:x.litros??'','PRECO INFORMADO/L':x.preco_litro??'','PRECO CALCULADO/L':C.ratio(x.valor,x.litros)??''}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),tipo==='diesel'?'ABASTECIMENTOS':'PEDÁGIOS');}}
  XLSX.writeFile(wb,template?'Layout_Frota_Premier.xlsx':'Frota_Premier.xlsx');
 }
 async function createPreview(){const f=$('fFile').files[0];if(!f)throw Error('Selecione uma planilha.');if(f.size>20*1024*1024)throw Error('Arquivo maior que 20 MB.');const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});preview=C.parseWorkbook(wb,XLSX,records,$('fDefaultOp').value);preview.filename=f.name;preview.rows.forEach(x=>x.selected=!!x.record&&!x.error&&!x.duplicate);renderPreview();$('fPreview').scrollIntoView({behavior:'smooth',block:'start'});}
 async function confirmImport(){const a=preview?.rows.filter(x=>x.selected&&x.record&&!x.error&&!x.duplicate).map(x=>C.payload(x.record))||[];if(!a.length)throw Error('Nenhuma linha válida selecionada.');if(!confirm('Importar '+a.length+' registros para todos? Linhas com avisos serão mantidas para conferência.'))return;
  busy=true;renderPreview();try{const canonical=JSON.stringify(a.map(x=>Object.fromEntries(C.fields.map(k=>[k,x[k]]))).sort((x,y)=>C.identity(x).localeCompare(C.identity(y))));const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));const hash=[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');const result=await request('rpc/frota_importar',{method:'POST',body:JSON.stringify({p_arquivo:preview.filename,p_fingerprint:hash,p_rows:a})});preview=null;busy=false;await loadFleet();notice(result.importados+' registros importados. '+result.duplicados+' duplicados ignorados.');}finally{busy=false;if(preview)renderPreview();}
 }
 const formFields=[['data','Data inicial','date'],['data_fim','Data final','date'],['operacao','Operação','select'],['placa','Placa','text'],['motorista','Motorista','text'],['km_inicial','KM inicial','text'],['km_final','KM final','text'],['km_declarado','KM total informado','text'],['diesel','Valor diesel','text'],['litros','Litros','text'],['preco_litro','Preço/litro','text'],['pedagio','Pedágio','text'],['partida','Ponto de partida','text'],['rota','Destino/rota','text'],['observacao','Observação','text']];
 let editId=null;
 function openForm(id=null){editId=id;const x=records.find(x=>x.id===id)||{data:new Date().toLocaleDateString('en-CA'),data_fim:'',operacao:'SP'};$('fFormTitle').textContent=id?'Editar registro da frota':'Adicionar registro da frota';$('fFormFields').innerHTML=formFields.map(([k,label,type])=>`<label>${label}${type==='select'?`<select name="${k}" required>${opOptions(x[k])}</select>`:`<input name="${k}" type="${type}" value="${escape(x[k]??'')}" ${['data','placa','motorista'].includes(k)?'required':''} ${['km_inicial','km_final','km_declarado','diesel','litros','preco_litro','pedagio'].includes(k)?'inputmode="decimal"':''}>`}</label>`).join('');$('fFormError').textContent='Para cálculos exatos, informe litros ou preço/L pago, além do valor diesel. Preço de mercado serve apenas como referência.';dialog.showModal();}
 async function saveForm(e){e.preventDefault();const button=$('fSave');button.disabled=true;try{const o=Object.fromEntries(new FormData($('fForm'))),v=C.validate(o);if(v.warnings.length&&!confirm(v.warnings.join('\n')+'\nSalvar com esses avisos?'))return;const body=C.payload(v.record);if(editId)await request('frota_registros?id=eq.'+editId,{method:'PATCH',body:JSON.stringify(body)});else await request('frota_registros',{method:'POST',body:JSON.stringify(body)});dialog.close();selected.clear();await loadFleet();notice('Registro salvo para todos.');}catch(e){$('fFormError').textContent=e.message;}finally{button.disabled=false;}}
 async function remove(ids){if(!ids.length)throw Error('Selecione registros para excluir.');if(!confirm('Excluir '+ids.length+' registros da frota para todos? O histórico de auditoria será preservado.'))return;await request('frota_registros?id=in.('+ids.join(',')+')',{method:'PATCH',body:JSON.stringify({deleted_at:new Date().toISOString()})});selected.clear();await loadFleet();notice(ids.length+' registros excluídos da visualização.');}
 async function handle(action,id){
  switch(action){case 'open-tolls':navigate('tolls');break;case 'reset':$('fStart').value=$('fEnd').value=$('fOp').value=$('fPlate').value=$('fDriver').value='';updateOptions();render();break;
  case 'truck':case 'driver':detail={type:action,name:id};render();break;case 'back-detail':detail=null;render();break;
  case 'add':openForm();break;case 'edit':openForm(Number(id));break;case 'delete':await remove([Number(id)]);break;
  case 'select-all':C.filtered(records,filters()).forEach(x=>selected.add(x.id));render();break;case 'clear-select':selected.clear();render();break;
  case 'delete-selected':await remove([...selected].filter(id=>rows().some(x=>x.id===id)));break;
  case 'template':exportWorkbook(true);break;case 'export':exportWorkbook();break;case 'preview':await createPreview();break;
  case 'confirm-import':await confirmImport();break;case 'cancel-preview':preview=null;render();break;
  case 'settings-save':{const a=Number($('fCostFactor').value),b=Number($('fKmFactor').value);if(!(a>1&&a<=10&&b>1&&b<=20))throw Error('Informe fatores maiores que 1, até 10 para custo e 20 para KM.');await request('frota_config?id=eq.1',{method:'PATCH',body:JSON.stringify({fator_custo:a,fator_km:b,updated_at:new Date().toISOString()})});await loadFleet();notice('Configurações salvas para todos.');break;}}
 }
 $('fToggle').addEventListener('click',()=>{const open=$('fMenu').hidden;$('fMenu').hidden=!open;$('fToggle').setAttribute('aria-expanded',String(open));});
 $('fMenu').addEventListener('click',e=>{const el=e.target.closest('[data-fpage]');if(el)navigate(el.dataset.fpage,el);});
 $('fMenu').addEventListener('keydown',e=>{if(e.key==='Escape'){$('fMenu').hidden=true;$('fToggle').setAttribute('aria-expanded','false');$('fToggle').focus();}if((e.key==='Enter'||e.key===' ')&&e.target.dataset.fpage){e.preventDefault();e.target.click();}});
 root.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||busy)return;try{await handle(b.dataset.action,b.dataset.id);}catch(e){notice(e.message,true);}});
 root.addEventListener('change',e=>{if(e.target.id==='fDieselType'){dieselType=e.target.value;render();return;}if(e.target.classList.contains('f-check')){const id=Number(e.target.dataset.id);e.target.checked?selected.add(id):selected.delete(id);return;}if(e.target.dataset.previewIndex!==undefined){preview.rows[Number(e.target.dataset.previewIndex)].selected=e.target.checked;return;}if(e.target.dataset.previewOperation!==undefined){const i=Number(e.target.dataset.previewOperation);preview.rows[i].record.operacao=e.target.value;preview.rows.forEach(x=>{if(x.conflict)x.error=null;});C.classify(preview.rows,records);preview.rows.forEach(x=>x.selected=!!x.record&&!x.error&&!x.duplicate);renderPreview();}});
 root.addEventListener('input',e=>{if(e.target.id==='fSearchToll')root.querySelectorAll('[data-toll-search]').forEach(r=>r.hidden=!r.dataset.tollSearch.includes(C.normalize(e.target.value)));if(e.target.id==='fSearchTruck')root.querySelectorAll('[data-search]').forEach(r=>r.hidden=!r.dataset.search.includes(C.normalize(e.target.value).replace(/[^A-Z0-9]/g,'')));});
 ['fStart','fEnd','fOp','fPlate','fDriver'].forEach(id=>$(id).addEventListener('change',()=>{selected.clear();if(id==='fOp')updateOptions();render();}));
 $('fForm').addEventListener('submit',saveForm);$('fCancel').addEventListener('click',()=>dialog.close());
 loadFleet();setInterval(loadFleet,30000);
})();
