const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../frota-core.js');
const xlsxPath=process.env.XLSX_TEST_BUNDLE;if(!xlsxPath)throw Error('Defina XLSX_TEST_BUNDLE para a versão 0.18.5 já usada pelo site.');
const X=require(xlsxPath);let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
const record={data:'2026-10-01',data_fim:'2026-10-01',operacao:'SP',placa:'ABC1D23',motorista:'ANA',km_inicial:100,km_final:200,km_declarado:100,diesel:50,litros:10,preco_litro:5,pedagio:20,partida:'BASE',rota:'VIAGEM',observacao:''};
test('duração inclusiva e virada do mês',()=>{assert.equal(C.days({data:'2026-09-27',data_fim:'2026-09-29'}),3);assert.equal(C.days({data:'2026-09-30',data_fim:'2026-10-02'}),3);assert.equal(C.days({data:'2026-10-08',data_fim:'2026-10-08'}),1);});
test('litros estimados e preço ponderado sem inventar consumo',()=>{const a={...C.validate(record).record,litros:null,preco_litro:5};let s=C.stats([a]);assert.equal(s.consumption,10);assert.equal(s.estimatedLiters,true);assert.equal(s.price,5);assert.equal(s.kml,null);s=C.stats([a,{...a,litros:20,diesel:120,preco_litro:6}]);assert.equal(s.price,170/30);assert.equal(s.consumption,200/30);assert.equal(C.stats([{...a,preco_litro:null}]).consumption,null);assert.equal(C.stats([a,{...a,litros:null,diesel:0,preco_litro:null}]).consumption,null);assert.equal(C.stats([{...a,litros:10}]).estimatedLiters,false);});
test('estimativa ANP separada do cálculo exato e datas sem preço futuro',()=>{const x={...C.validate(record).record,data:'2026-09-27',data_fim:'2026-09-29',operacao:'BSB',km_total:2037,diesel:2881.37,litros:null,preco_litro:null};assert.equal(C.analysis([x]).consumption,null);const e=C.estimate([x]);assert.equal(e.price,7.41);assert(Math.abs(e.liters-2881.37/7.41)<1e-8);assert(Math.abs(e.kml-2037*7.41/2881.37)<1e-8);assert.equal(C.marketReference({...x,data:'2026-09-22'}).price,7.34);assert.equal(C.marketReference({...x,data:'2026-10-08'}).fallback,true);assert.equal(C.marketReference({...x,data:'2026-09-01'}),null);assert.equal(C.estimate([{...x,preco_litro:7}]).price,7);assert.equal(C.estimate([x,{...x,diesel:null}]).kml,null);assert.equal(C.estimate([x,{...x,diesel:0,km_total:100}]).kml,2137/(2881.37/7.41));assert.equal(C.estimate([x],'S500').price,7.19);});
test('números brasileiros, zero e ausência',()=>{assert.equal(C.number('R$ 1.234,50'),1234.5);assert.equal(C.number('123,5'),123.5);assert.equal(C.number(123.5),123.5);assert.equal(C.number(0),0);assert.equal(C.number(''),null);assert.equal(C.number('….'),null);assert.throws(()=>C.number('abc'));assert.throws(()=>C.number('-1'));});
test('datas, anos curtos, serial e intervalo real',()=>{assert.equal(C.date('01/10/26'),'2026-10-01');assert.deepEqual(C.period('27/09/2026 Á 29/09/2026'),['2026-09-27','2026-09-29']);assert.throws(()=>C.date('31/02/26'));assert.throws(()=>C.period('02/10/26','01/10/26'));assert.equal(C.date(new Date('2026-10-01T00:00:00Z')),'2026-10-01');});
test('normaliza placa e motorista sem vínculo permanente',()=>{const x=C.validate({...record,placa:' abc-1d23 ',motorista:' Ana  Silva '}).record;assert.equal(x.placa,'ABC1D23');assert.equal(x.motorista,'ANA SILVA');assert.throws(()=>C.validate({...record,placa:'INVÁLIDA'}));});
test('KM calculado e divergência preservada',()=>{const x=C.validate({...record,km_declarado:99});assert.equal(x.record.km_total,100);assert.equal(x.record.km_declarado,99);assert(x.warnings.some(x=>x.includes('Divergência')));assert.throws(()=>C.validate({...record,km_final:90}));});
test('KM incompleto preserva combustível conhecido',()=>{const x=C.validate({...record,km_final:'….',km_declarado:'….',diesel:859.99}).record;assert.equal(x.km_total,null);const s=C.stats([x]);assert.equal(s.pending,1);assert.equal(s.cost,879.99);assert.equal(s.cpkm,null);});
test('razões de somas e litros completos',()=>{const x=C.validate(record).record,s=C.stats([x,{...x,km_total:300,diesel:100,litros:20,pedagio:0}]);assert.equal(s.cpkm,170/400);assert.equal(s.kml,400/30);assert.equal(s.price,5);assert.equal(C.stats([{...x,litros:null}]).kml,null);assert.equal(C.stats([{...x,pedagio:null}]).toll,null);});
test('filtros simultâneos e viagem cruzando período',()=>{const x=C.validate(record).record,b={...x,operacao:'BSB',data:'2026-09-27',data_fim:'2026-09-29',motorista:'BIA'};assert.equal(C.filtered([x,b],{start:'2026-09-28',end:'2026-09-28',operation:'BSB',driver:'BIA',plate:'ABC1D23'}).length,1);assert.equal(C.filtered([x,b],{operation:'FAZ'}).length,0);});
test('duplicados e conflitos com custo diferente',()=>{const x=C.validate(record).record,a=[{record:{...x},warnings:[]},{record:{...x},warnings:[]}];C.classify(a,[]);assert(!a[0].duplicate);assert(a[1].duplicate);const b=[{record:{...x,diesel:51},warnings:[]}];C.classify(b,[x]);assert(b[0].conflict);assert(b[0].error);});
test('várias viagens na mesma placa/data',()=>{assert.notEqual(C.identity(C.validate(record).record),C.identity(C.validate({...record,km_inicial:200,km_final:300}).record));});
test('correção de hodômetro final não duplica uma viagem',()=>{const x=C.validate(record).record,a=[{record:C.validate({...record,km_final:210,km_declarado:110}).record,warnings:[]}];C.classify(a,[x]);assert(a[0].conflict);});
test('alerta de continuidade usa todo histórico',()=>{const a={...C.validate(record).record,id:1},b={...a,id:2,data:'2026-10-02',data_fim:'2026-10-02',km_inicial:205,km_final:300,km_total:95,km_declarado:95};assert(C.alerts([b],[a,b]).some(x=>x.message.includes('200 → inicial 205')));});
test('layout exportado é reimportável com dados tipados',()=>{const x=C.validate(record).record,wb=X.utils.book_new();X.utils.book_append_sheet(wb,X.utils.json_to_sheet(C.exportRows([x]),{header:C.HEADERS}),'IMPORTAÇÃO');const bytes=X.write(wb,{type:'buffer',bookType:'xlsx'});const parsed=C.parseWorkbook(X.read(bytes,{type:'buffer',cellDates:true}),X);assert.equal(parsed.rows.length,1);assert.equal(parsed.rows[0].record.diesel,50);assert.equal(parsed.rows[0].record.operacao,'SP');C.classify(parsed.rows,[x]);assert(parsed.rows[0].duplicate);});
test('cabeçalho após título e aba sem dados',()=>{const wb=X.utils.book_new();X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet([['TÍTULO'],C.HEADERS,C.HEADERS.map((h,i)=>C.exportRows([C.validate(record).record])[0][h])]),'Dados');X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet([['Instruções']]),'Guia');const p=C.parseWorkbook(wb,X);assert.equal(p.rows.length,1);assert.equal(p.issues.length,1);});
test('estrutura inválida e cabeçalhos duplicados bloqueados',()=>{const wb=X.utils.book_new();X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet([['DATA','PLACA','MOTORISTA','KM TOTAL','KM TOTAL']]),'Inválida');assert.throws(()=>C.parseWorkbook(wb,X));});
if(process.env.FROTA_REAL_ODS){test('planilha real: 30 registros reconciliados com valores de origem',()=>{const wb=X.read(fs.readFileSync(process.env.FROTA_REAL_ODS),{type:'buffer',cellDates:true}),p=C.parseWorkbook(wb,X),a=p.rows.map(x=>x.record),s=C.stats(a);assert.equal(p.rows.length,30);assert.equal(p.rows.filter(x=>x.error).length,0);assert.equal(s.plates,3);assert.equal(s.drivers,2);const numeric=v=>typeof v==='number'?v:Number(String(v).replace(/\./g,'').replace(',','.'));const fuel=p.rows.reduce((t,x)=>t+numeric(x.record.origem.valores.diesel),0);const km=p.rows.reduce((t,x)=>t+(Number.isFinite(numeric(x.record.origem.valores.km_final))?numeric(x.record.origem.valores.km_final)-numeric(x.record.origem.valores.km_inicial):0),0);assert(Math.abs(s.fuel-fuel)<.001);assert.equal(s.km,km);assert.equal(s.toll,null);assert.equal(s.kml,null);assert.equal(a.filter(x=>x.operacao==='BSB').length,1);assert(p.rows.some(x=>x.warnings.some(s=>s.includes('Hodômetro anterior'))));});}
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8'),original=process.env.KM_BASE_HTML?fs.readFileSync(process.env.KM_BASE_HTML,'utf8'):null;
test('JavaScript de KM preservado byte a byte',()=>{const inline=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(inline);if(original)assert.equal(inline,original.match(/<script>([\s\S]*?)<\/script>/)[1]);assert.equal((html.match(/onclick="go\(/g)||[]).length,6);});
console.log(count+' verificações passaram. Cálculos locais verificados; validação visual da alteração executada separadamente.');
